seed: 0

data:
  image_height: 128
  image_width: 128

model:
  encoder:
    type: vit
    vit_encoder_patch_size: 16
    vit_encoder_dim: 512
    vit_encoder_num_layers: 4
    vit_encoder_num_heads: 12
    vit_encoder_mlp_dim: 512
    use_image_augmentation: False
  pretrained_encoder: null
  bc_policy:
    type: lstm # 'mlp', 'lstm', or 'gpt'
    hidden_size: 512
    num_layers: 2
    lstm_hidden_size: 512
    lstm_num_layers: 2
  learning_rate: 3e-4
  lr_warmup_steps: 25000
  joystick_loss_weight: 1.0
  button_loss_weight: 1.0
  train_from_embeddings: False

