seed: 0

data:
  image_height: 128
  image_width: 128

model:
  encoder:
    type: resnet
    cnn_encoder_dim: 2
    cnn_encoder_start_channels: 16
    use_image_augmentation: False
  pretrained_encoder: null
  bc_policy:
    type: lstm # 'mlp', 'lstm', or 'gpt'
    hidden_size: 512
    num_layers: 2
    lstm_hidden_size: 512
    lstm_num_layers: 2
  learning_rate: 3e-4
  lr_warmup_steps: 0 # use no warmup
  joystick_loss_weight: 1.0
  button_loss_weight: 1.0
  train_from_embeddings: False
